In [1]:
import torch

In [2]:
x=torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [9]:
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

构造数组作为神经网络中的参数时
通常会随机初始化参数的值
以下代码每个元素都从均值0、标准差为1的标准高斯分布中随机采样得到

In [10]:
torch.rand(3,4)

tensor([[0.6445, 0.9892, 0.8733, 0.7897],
        [0.2406, 0.6255, 0.1438, 0.2543],
        [0.1892, 0.5891, 0.9064, 0.5131]])

In [14]:
x=torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
x


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [15]:
y=torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
x+y,x-y,x*y,x/y,x**y

(tensor([[ 2,  4,  6,  8, 10],
         [12, 14, 16, 18, 20]]),
 tensor([[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]),
 tensor([[  1,   4,   9,  16,  25],
         [ 36,  49,  64,  81, 100]]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[          1,           4,          27,         256,        3125],
         [      46656,      823543,    16777216,   387420489, 10000000000]]))

In [16]:
torch.cat((x,y),dim=0)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [17]:
torch.cat((x,y),dim=1)

tensor([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])