In [1]:
import torch

In [2]:
x=torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [9]:
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [3]:
"""
构造数组作为神经网络中的参数时
通常会随机初始化参数的值
以下代码每个元素都从均值0、标准差为1的标准高斯分布中随机采样得到
"""

'\n构造数组作为神经网络中的参数时\n通常会随机初始化参数的值\n以下代码每个元素都从均值0、标准差为1的标准高斯分布中随机采样得到\n'

In [10]:
torch.rand(3,4)

tensor([[0.6445, 0.9892, 0.8733, 0.7897],
        [0.2406, 0.6255, 0.1438, 0.2543],
        [0.1892, 0.5891, 0.9064, 0.5131]])

In [14]:
x=torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
x


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [15]:
y=torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
x+y,x-y,x*y,x/y,x**y

(tensor([[ 2,  4,  6,  8, 10],
         [12, 14, 16, 18, 20]]),
 tensor([[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]),
 tensor([[  1,   4,   9,  16,  25],
         [ 36,  49,  64,  81, 100]]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[          1,           4,          27,         256,        3125],
         [      46656,      823543,    16777216,   387420489, 10000000000]]))

In [16]:
torch.cat((x,y),dim=0)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [17]:
torch.cat((x,y),dim=1)

tensor([[ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10]])

In [1]:
#拼接

In [21]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [22]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [23]:
#穿插练习

In [25]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [24]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [27]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [4]:
X.sum()

tensor(66.)

In [5]:
#广播机制（broadcast mechanism）

In [6]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [7]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
#穿插练习

In [34]:
a = torch.zeros(3,3,1)
b = torch.ones(3,1,2)
a, b

(tensor([[[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.]]]),
 tensor([[[1., 1.]],
 
         [[1., 1.]],
 
         [[1., 1.]]]))

In [35]:
a+b

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [28]:
#索引和切片

In [8]:
X[0]

tensor([0., 1., 2., 3.])

In [9]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [10]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [13]:
X[:,0:2]=1
X

tensor([[ 1.,  1., 12., 12.],
        [ 1.,  1., 12., 12.],
        [ 1.,  1., 10., 11.]])

In [14]:
#节省内存

In [17]:
before=id(Y)
Y=X+Y
id(Y)==before

False

In [ ]:
#使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>。

In [18]:
Z = torch.zeros_like(Y)
print("idZ:",id(Z))
Z[:] = X + Y
print("idZ:",id(Z))

idZ: 3098823981488
idZ: 3098823981488


In [19]:
#或者使用X += Y来减少操作的内存开销。

In [20]:
before=id(X)
X+=Y
id(X) == before

True